### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [8]:
n = int(input())
Z = np.arange(n)
Z = Z[::-1]
print(Z)

10
[9 8 7 6 5 4 3 2 1 0]


### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [44]:
N = int(input('Введите количество элементов: '))
a = np.diag(np.arange(0,4))
print(a)

sum_ = 0        
for i in range(len(a)):     
    sum_ += a[i][i]
sum_

Введите количество элементов: 4
[[0 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]


6

### Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [46]:
"""4x + 2y + z = 4
   x + 3y = 12
   5y + 4z = -3"""
from numpy import linalg
a = np.array([ [4,2,1], [1,3,0], [0,5,4] ])
b = np.array([4,12,-3])
linalg.solve(a,b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [47]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

### Задание 4
В материалах занятия раздел “Задача 4 домашнего задания”
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем.
На сайт заходит очередной посетитель, о покупках которого известно следующее: next_user_stats = np.array([0, 1, 2, 0, 0, 0])
Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [92]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], np.int32)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
a = 360
j = 0

for x in users_stats:
    aLength = np.linalg.norm( x )
    bLength = np.linalg.norm( next_user_stats )
    y = np.arccos(np.dot( x, next_user_stats ) / ( aLength * bLength )) * 360 / 2 / np.pi
    j += 1  
    if y < a:
        a = y
        id = j
print( f'Самый похожий пользователь с id {id}')

Самый похожий пользователь с id 8
